# Simplified Azure DevOps pipeline - Build and Test Only
# This version removes Azure deployment tasks to avoid service connection issues
# Deploy manually using the artifacts created by this pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build and Test
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests  # Additional testing dependencies
      displayName: Install Python dependencies

    - script: |
        # Run unit tests
        python -m pytest tests/ -v --tb=short
      displayName: Run Unit Tests
      continueOnError: false

    - script: |
        # Validate application can import without errors
        python -c "
        import sys, os
        sys.path.append('src')
        from src.data_processor import DataProcessor
        from src.analyzers import RecurringIssuesAnalyzer, SLAAnalyzer
        from src.utils import DataUtils
        print('✓ All imports successful')
        "
      displayName: Validate Application Imports

    - script: |
        # Test Streamlit app syntax
        python -m streamlit run app.py --help
      displayName: Validate Streamlit App Syntax

    - task: ArchiveFiles@2
      displayName: Create deployable zip
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'
        verbose: false
        # Exclude common non-deployables
        # Note: Adjust exclusions if needed
        tarCompression: 'gz'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Unit Tests'

    - script: |
        echo "✅ Build completed successfully!"
        echo "📦 Deployment package created: site.zip"
        echo "🚀 Ready for manual deployment to Azure"
        echo ""
        echo "To deploy manually:"
        echo "1. Download the 'drop' artifact from this pipeline run"
        echo "2. Extract site.zip"
        echo "3. Deploy to Azure App Service via:"
        echo "   - Azure Portal (Deployment Center)"
        echo "   - VS Code Azure extension"
        echo "   - Azure CLI: az webapp deploy"
      displayName: Build Summary and Next Steps 